# https://github.com/catppuccin/alacritty
[general]
import = [
  #"~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/themes/themes/github_light.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"


[font]
normal.family = "MesloLGS Nerd Font"
bold.family = "MesloLGS Nerd Font"
italic.family = "MesloLGS Nerd Font"
bold_italic.family = "MesloLGS Nerd Font"

